# Generated by Django 3.2.8 on 2021-10-15 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=128)),
                ('uvas', models.CharField(max_length=128)),
                ('tipo', models.CharField(max_length=32)),
                ('acucar', models.CharField(max_length=32)),
                ('safra', models.IntegerField()),
                ('nacionalidade', models.CharField(max_length=32)),
                ('vinicola', models.CharField(max_length=32)),
                ('reserva', models.CharField(max_length=32)),
                ('alcool', models.IntegerField()),
                ('temperatura', models.IntegerField()),
                ('volume', models.IntegerField()),
                ('amadurecimento', models.CharField(max_length=128)),
                ('guarda', models.IntegerField()),
                ('visual', models.CharField(max_length=32)),
                ('olfativo', models.TextField(max_length=256)),
                ('gustativo', models.TextField(max_length=256)),
            ],
        ),
    ]
